# Generated by Django 4.0.2 on 2022-05-12 10:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newssection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='detail',
            field=tinymce.models.HTMLField(),
        ),
    ]
